export const ItemActionTypes = {
    TOGGLE_ITEM_FORM: "TOGGLE_ITEM_FORM",
    CREATE_ITEM: "CREATE_ITEM",
    EDIT_ITEM: "EDIT_ITEM",
    DELETE_ITEM: "DELETE_ITEM",
    TOGGLE_EDIT_MODE: "TOGGLE_EDIT_MODE",
    SET_CURRENT_ITEM: "SET_CURRENT_ITEM",
}