export const NoteActionTypes = {
    TOGGLE_NOTE_FORM: "TOGGLE_NOTE_FORM",
    CREATE_NOTE: "CREATE_NOTE",
    EDIT_NOTE: "EDIT_NOTE",
    DELETE_NOTE: "DELETE_NOTE",
    TOGGLE_EDIT_MODE: "TOGGLE_EDIT_MODE",
    SET_CURRENT_NOTE: "SET_CURRENT_NOTE",
}