export const TodoActionTypes = {
    TOGGLE_TODO_FORM: "TOGGLE_TODO_FORM",
    CREATE_TODO: "CREATE_TODO",
    EDIT_TODO: "EDIT_TODO",
    DELETE_TODO: "DELETE_TODO",
    TOGGLE_EDIT_MODE: "TOGGLE_EDIT_MODE",
    CHECK_DONE_TODO: "CHECK_DONE_TODO",
    SET_CURRENT_TODO: "SET_CURRENT_TODO",
}